version: "3.9"

services:
  busik_rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: busik_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
      - "1883:1883"
    networks:
      - busik

networks:
  busik:
    name: busik
    attachable: true
